# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!
  PROJ_PATH: '"$PWD"'

tasks:
  build:
    desc: "Build the image"
    cmds:
      - docker build -t rexpaint-converter .
  run-converter:
    desc: "Runs the app. Pass the absolute path to the image you want to run against. First arg is file, second is scaling."
    cmds:
      - |
        read -p "Image or image dir to run convert on " IMAGE_DIR
        read -p "Pixel side length of chunks, min 3, smaller = better resolution " SCALING
        read -p "G: More granular character selections S: Simpler character selections " GRANULARITY
        read -p "Black and white terminal output: y/N  " BW
        docker run --rm -v {{.PROJ_PATH}}/outputs:/rexpaint/outputs -v {{.PROJ_PATH}}/$IMAGE_DIR:/rexpaint/inputs rexpaint-converter $SCALING $GRANULARITY $BW
  get-image:
    - |
      read -p "Dir where images to be converted are" IMAGE_DIR;
      docker run -it --entrypoint /bin/bash -v {{.PROJ_PATH}}/outputs:/rexpaint/outputs -v {{.PROJ_PATH}}/$IMAGE_DIR:/rexpaint/inputs rexpaint-converter
  build-args:
    desc: "CLI args you can pass to the container are"